### ISSUE TITLE
Safari 5.0 Errors on Live Site

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#152]
Hi Kelsy,

Has something changed re: Pathways overnight?

This morning using my Safari 5.0.6 I no longer get access to items in my black menu bar, and all my specialty displays are blank, much like you were describing for IE 8 and 9.  It works fine on my laptop using Safari 7.0.  Any idea why this changed overnight?

Perhaps you are just trying to convince me to buy that new iMac now.

Ron

- attempted to access live and test site using safari 5.0 for windows (through linux wine)
- timed out for both, "server where the page is located isn't responding"
- tested master branch locally with the same, and everything seems to be working fine..
- tested live site on safari 5.1.5 on browserstack, seemed to be working fine...

**Comment by bgracie** [comment]
tested with safari 5.0 in browserstack, on main page unable to activate dropdown menus, and get this in the error console:

TypeError: Result of expression 'd.prototype[b]' [undefined] is not an object.
/asset-files/application-304c218f6cf5db925110ce9804e4fe9b.js:257TypeError: Result of expression 'o.createElement.bind' [undefined] is not a function.
/#:89Unmatched </head> encountered.  Ignoring tag.
/#:90Extra <body> encountered.  Migrating attributes back to the original <body> element and ignoring the tag.
/#:1062Unmatched </p> encountered.  Converting </p> into <p></p>.
/#:64TypeError: Result of expression '$('#search').livesearch' [undefined] is not a function.

**Comment by KelseyDH** [comment]
might just solve this by disabling react and charts until we start using them in the project

**Comment by bgracie** [comment]
yeah if that works let's do it

**Comment by KelseyDH** [comment]
highcharts supposedly still supports Safari 5 http://www.highcharts.com/documentation/compatibility/

**Comment by bgracie** [comment]
https://github.com/facebook/react/issues/273

**Comment by KelseyDH** [comment]
Closing this until we need to use react again.

**Comment by bgracie** [comment]
maybe try using MDN's polyfill for Function.prototype.bind

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind

**Comment by KelseyDH** [comment]
Let me know if it works for resolving these issues if you test it out!
